### ISSUE TITLE
Can you build individual predicates, then combine them after? 

### ISSUE THREAD

**Issue by chadbrochill317** [andreadelfante/PredicateFlow#10]

**Comment by andreadelfante** [comment]
Hi, thank you to open this issue. 
Would you be able to provide me an example to learn more about this issue?

**Comment by robmontesinos** [comment]
I have the same question. I am using Realm. Here is an example :

```
var predicates: [NSPredicate] = []
let userNames = ["user1", "user41", "user88", "user4329"]
for userName in userNames {
    let predicate = NSPredicate(format: "userName == %@", userName)
    predicates.append(predicate)
}

let compoundPredicate = NSCompoundPredicate(type: .and, subpredicates: predicates)
```

Can your library help with the above task? Thank you very much

**Comment by andreadelfante** [comment]
Hi @robmontesinos, for compound predicate you can use the PredicateBuilder.
Assuming MyClass is the class containing the field `userName`:
```swift
PredicateBuilder(MyClassSchema.userName.is("user1"))
    .and(MyClassSchema.userName.is("user41"))
    .and(MyClassSchema.userName.is("user88"))
    .and(MyClassSchema.userName.is("user4329"))
    .build()
```

To build a single predicate just type:
```swift
MyClassSchema.userName.is("user1").predicate
```
and then you can combine it later with PredicateBuilder or NSCompountPredicate.

**Comment by robmontesinos** [comment]
Thank you @andreadelfante - very cool solution
