### ISSUE TITLE
PredicateFlow-Realm.stencil' does not exist or is not readable.

### ISSUE THREAD

**Issue by phlippieb** [andreadelfante/PredicateFlow#11]
I followed the installation instructions (with the PredicateFlow-Realm part), but I get this error:

> `error: '/Users/[...]/Pods/PredicateFlow/PredicateFlow/Templates/PredicateFlow-Realm.stencil' does not exist or is not readable.`

Indeed, after adding `pod 'PredicateFlow/Realm'` to my Podfile and running `pod install`, my `Pods/PredicateFlow`-directory does not contain any `.stencil` files.

I'm running Xcode Version 10.3 with CocoaPods 1.7.5.

**Comment by phlippieb** [comment]
Update: looks like you need **both** `pod 'PredicateFlow` **and**  `pod 'PredicateFlow/Realm'` in your PodFile.

**Comment by andreadelfante** [comment]
Thank you for the issue! I'll update the installation instructions.
