### ISSUE TITLE
Compiling for iOS 8.0, but module 'RealmSwift' has a minimum deployment target of iOS 9.0

### ISSUE THREAD

**Issue by phlippieb** [andreadelfante/PredicateFlow#16]
PredicateFlow doesn't compile when installed on a fresh project through CocoaPods. This seems to be because it is configured with a minimum deployment target of iOS 8.0, while depending on RealmSwift, which is configured with a minimum target of 9.0.

To reproduce:

1. Create a new iOS project
2. `pod init`
3. Add `pod 'PredicateFlow'` and `pod 'PredicateFlow/Realm'` to the podfile
4. `pod install`
5. Build your workspace

You should see an error like 

```
Compiling for iOS 8.0, but module 'RealmSwift' has a minimum deployment target of iOS 9.0: /.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/RealmSwift/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

I think it would be fixed by changing this library's CocoaPods configuration so that the minimum deployment target is 9.0.

**Comment by andreadelfante** [comment]
Thank you! I'm gonna deploy 1.4 version on Cocoapods!
